# Zloada se xresources in xbindkeys
[[ -f ~/.Xresources ]]&& xrdb -merge -I$HOME ~/.Xresources &
xbindkeys &

# The black/white grid as background doesn't suit my taste.
xsetroot -solid black &
# Ratpoison is compatible with xcompmgr! Now you can have real transparency
xcompmgr -c -f -D 5 &
# Set keyboard layout
setxkbmap -layout si &
# fire up ratpoison!
exec /usr/bin/ratpoison
